const express = require("express")
const router = express.Router()
const userController = require("../../server/Controller/userController")

router.post("/inscription",userController.inscription)
router.post("/connexion",userController.connexion)
router.post("/selection",userController.selection)
router.post("/modifications",userController.modifications)
router.get('/touuser',userController.touuser)
router.post("/AjoutCategories",userController.AjoutCategories)
router.get("/AllCategories",userController.AllCategories)
router.post("/addpublication",userController.addpublication)
router.post('/getPublicationspecify',userController.getPublicationspecify)
router.post("/getpublicationDescription",userController.getpublicationDescription)
router.post("/insertComment",userController.insertComment)
router.post('/getCommentairesSpecifyPublications',userController.getCommentairesSpecifyPublications)
router.get("/getLastPublication",userController.getLastPublication)
router.get("/getallPUblication",userController.getallPUblication)
router.get("/getmostPUblicatores",userController.getmostPUblicatores)
router.post("/getforsearch",userController.getforsearch)
router.post("/getPUblicationsforuser",userController.getPUblicationsforuser)
module.exports = router